/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/UIIg2OtjIGA
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

import Link from "next/link";
import Image from "next/image";

export function Hero() {
  return (
    <section className="w-full flex justify-center sm:h-[80vh] items-center h-[50vh] mt-28 z-50">
      <div className="container px-4 md:px-6  ">
        <div className="grid gap-8 lg:grid-cols-[1fr_500px] lg:gap-12 xl:grid-cols-[1fr_600px]">
          <div className="flex flex-col justify-center space-y-4">
            <div className="space-y-2">
              <h1 className="text-[#edede9] text-4xl font-bold tracking-tighter sm:text-5xl md:text-6xl lg:text-7xl">
                Streamline Your Workflow with Our SaaS Platform
              </h1>
              <p className="max-w-[600px] text-[#d6ccc2] text-muted-foreground md:text-xl lg:text-lg xl:text-xl">
                Boost productivity, enhance collaboration, and scale your
                business with our cutting-edge SaaS solution.
              </p>
            </div>
            <div className="flex flex-col gap-2 min-[400px]:flex-row">
              <Link
                href="#"
                className="inline-flex h-10 items-center bg-[#d6ccc2] text-black/80 justify-center rounded-md  px-8 text-sm font-medium  shadow-2xl transition-colors  focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
                prefetch={false}
              >
                Sign Up
              </Link>
              <Link
                href="#"
                className="inline-flex h-10 items-center justify-center rounded-md border border-[#d6ccc2] hover:bg-[#d6ccc2] hover:text-black/80 border-input px-8 text-sm font-medium shadow-sm transition-colors  text-[#d6ccc2] focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
                prefetch={false}
              >
                Learn More
              </Link>
            </div>
          </div>
          <Image
            src="/stats2.svg"
            width="750"
            height="750"
            alt="Hero"
            className="mx-auto aspect-video overflow-hidden rounded-xl object-cover sm:w-full lg:order-last lg:aspect-square"
          />
        </div>
      </div>
    </section>
  );
}
